name: Push Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '10.3.0', '10.18.1', '11.15.0', '12.4.0', '12.8.1', '12.10.0', '13.1.0', '13.7.0' ]
    name: Build using Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install Node packages
        run: npm install
      - name: Setup lerna
        run: npx lerna bootstrap
      - name: Build
        run: gulp build
      - name: Lint
        run: gulp lint
      - name: Test
        run: gulp test
  coverage:
    runs-on: ubuntu-latest
    name: Generate coverage
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '13.7.0'
      - name: Install Node packages
        run: npm install
      - name: Setup lerna
        run: npx lerna bootstrap
      - name: Build
        run: gulp build
      - name: Run coverage
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l TypeScript -r build/coverage/lcov.info
        env:
            CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_KEY }}
